[tool.poetry]
name = "granary"
version = "0.3.0"
description = ""
authors = ["Tuvix Shih <tuvix@ninthday.info>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
fastapi = "^0.100.0"
uvicorn = "^0.22.0"
paho-mqtt = "^2.1.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
ruff = "^0.11.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
